//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcResourceLang.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcResourceLang.Resources.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once there were two mice. They were friends. One mouse lived in the country; the other mouse lived in the city. After many years the Country mouse saw the City mouse; he said, &quot;Do come and see me at my house in the country.&quot; So the City mouse went. The City mouse said, &quot;This food is not good, and your house is not good. Why do you live in a hole in the field? You should come and live in the city. You would live in a nice house made of stone. You would have nice food to eat. You must come and see me at my ho [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ArticleDisplay {
            get {
                return ResourceManager.GetString("ArticleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AuthorDisplay {
            get {
                return ResourceManager.GetString("AuthorDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPwdDisplay {
            get {
                return ResourceManager.GetString("ConfirmPwdDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm passwords do not match.
        /// </summary>
        public static string ConfirmPwdErrorDisplay {
            get {
                return ResourceManager.GetString("ConfirmPwdErrorDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeDisplay {
            get {
                return ResourceManager.GetString("HomeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon.
        /// </summary>
        public static string LogonDisplay {
            get {
                return ResourceManager.GetString("LogonDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName or Password can&apos;t be empty.
        /// </summary>
        public static string LogonErrorMsgDisplay {
            get {
                return ResourceManager.GetString("LogonErrorMsgDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have not account, please click.
        /// </summary>
        public static string NoteDisplay {
            get {
                return ResourceManager.GetString("NoteDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PwdDisplay {
            get {
                return ResourceManager.GetString("PwdDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterDisplay {
            get {
                return ResourceManager.GetString("RegisterDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Fail.
        /// </summary>
        public static string RegisterFailDisplay {
            get {
                return ResourceManager.GetString("RegisterFailDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Success.
        /// </summary>
        public static string RegisterSucDisplay {
            get {
                return ResourceManager.GetString("RegisterSucDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me?.
        /// </summary>
        public static string RemDisplay {
            get {
                return ResourceManager.GetString("RemDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City Mouse and the Country Mouse.
        /// </summary>
        public static string TitleDisplay {
            get {
                return ResourceManager.GetString("TitleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserDisplay {
            get {
                return ResourceManager.GetString("UserDisplay", resourceCulture);
            }
        }
    }
}
