//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcResourceLang.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcResourceLang.Resources.zh-CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从前，有两只老鼠，它们是好朋友。一只老鼠居住在乡村，另一只住在城里。很多年以后，乡下老鼠碰到城里老鼠，它说：“你一定要来我乡下的家看看。”于是，城里老鼠就去了。乡下老鼠领着它到了一块田地上它自己的家里。它把所有最精美食物都找出来给城里老鼠。城里老鼠说：“这东西不好吃，你的家也不好，你为什么住在田野的地洞里呢？你应该搬到城里去住，你能住上用石头造的漂亮房子，还会吃上美味佳肴，你应该到我城里的家看看。”
        ///
        ///乡下老鼠就到城里老鼠的家去。房子十分漂亮，好吃的东西也为他们摆好了。可是正当他们要开始吃的时候，听见很大的一阵响声，城里的老鼠叫喊起来：“快跑！快跑！猫来了！”他们飞快地跑开躲藏起来。
        ///
        ///过了一会儿，他们出来了。当他们出来时，乡下老鼠说：“我不喜欢住在城里，我喜欢住在田野我的洞里。因为这样虽然贫穷但是快乐自在，比起虽然富有却要过着提心吊胆的生活来说，要好些。”.
        /// </summary>
        public static string ArticleDisplay {
            get {
                return ResourceManager.GetString("ArticleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        public static string AuthorDisplay {
            get {
                return ResourceManager.GetString("AuthorDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认密码.
        /// </summary>
        public static string ConfirmPwdDisplay {
            get {
                return ResourceManager.GetString("ConfirmPwdDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码和确认密码不一致.
        /// </summary>
        public static string ConfirmPwdErrorDisplay {
            get {
                return ResourceManager.GetString("ConfirmPwdErrorDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        public static string HomeDisplay {
            get {
                return ResourceManager.GetString("HomeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string LogonDisplay {
            get {
                return ResourceManager.GetString("LogonDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名或密码不能为空.
        /// </summary>
        public static string LogonErrorMsgDisplay {
            get {
                return ResourceManager.GetString("LogonErrorMsgDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果你还没有账号，请点击.
        /// </summary>
        public static string NoteDisplay {
            get {
                return ResourceManager.GetString("NoteDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string PwdDisplay {
            get {
                return ResourceManager.GetString("PwdDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string RegisterDisplay {
            get {
                return ResourceManager.GetString("RegisterDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册失败.
        /// </summary>
        public static string RegisterFailDisplay {
            get {
                return ResourceManager.GetString("RegisterFailDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册成功.
        /// </summary>
        public static string RegisterSucDisplay {
            get {
                return ResourceManager.GetString("RegisterSucDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住我？.
        /// </summary>
        public static string RemDisplay {
            get {
                return ResourceManager.GetString("RemDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 城里老鼠和乡下老鼠.
        /// </summary>
        public static string TitleDisplay {
            get {
                return ResourceManager.GetString("TitleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户.
        /// </summary>
        public static string UserDisplay {
            get {
                return ResourceManager.GetString("UserDisplay", resourceCulture);
            }
        }
    }
}
